### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by redstar2k1** [shr00mie/gmapslocsharing#5]
Running HomeAssistant 0.98.1 on Ubuntu 18.04 LTS under /srv env.
Installed the deps in the /srv/homeassistant/lib/python3.6/site-packages, google_maps in the /home/homeassistant/.homeassistant/custom_components
Added the configuration part with debug true.
When I (re)start HA, I get a "ERROR (SyncWorker_8) [custom_components.google_maps.device_tracker] Google Maps - Component configuration failed: list index out of range." error and the tracker is not working.
Are there any other steps that I need to do, like log in Chrome from the same computer/user that runs HA? I have 2FA activated but I get no prompt on my phone to allow login when using the regular account password. Also tried setting a App Password in the account security and use that one but it's the same.

**Comment by shr00mie** [comment]
alright...first things first...

check under `/srv/homeassistant/lib/` and make sure that the rest of your packages aren't under python3.7 instead of python3.6. if you got most of your stuff under 3.7, then move the necessary packages under the appropriate python version.

if it's under python3.6, then make sure you have all the latest custom components and deps contents from the master branch.

set debug to True under the google_maps component and then in your configuration.yaml or wherever you have logger configured, set as below:

```yaml
## -------------------------------=[ Logger ]=------------------------------- ##
logger:
  default: info
  logs:
    gmapslocsharing: debug
```

then give her an ole restart and after maybe 4-5 minutes, run the below:
`cat /car/log/syslog | grep gmaps`

**Comment by redstar2k1** [comment]
Here is all I get from logs regarding this:
Sep  2 21:22:07 server hass[428]: 2019-09-02 21:22:07 DEBUG (SyncWorker_18) [gmapslocsharing] Initializing GoogleMaps module.
Sep  2 21:22:07 server hass[428]: 2019-09-02 21:22:07 DEBUG (SyncWorker_18) [gmapslocsharing.core.config] Initializing Config module.
Sep  2 21:22:07 server hass[428]: 2019-09-02 21:22:07 ERROR (SyncWorker_18) [custom_components.google_maps.device_tracker] Google Maps - Component configuration failed: list index out of range.
Attached is a list of the /srv/homeassistant/lib/python3.6/site-packages
[site-packages.txt](https://github.com/shr00mie/gmapslocsharing/files/3566891/site-packages.txt)

**Comment by shr00mie** [comment]
@redstar2k1 packages look good. can you confirm that you have the custom component foldered properly and that google-chrome-stable is installed?

**Comment by redstar2k1** [comment]
root@server:/home/homeassistant/.homeassistant/custom_components/google_maps# ls -al
total 28
drwxr-xr-x 3 homeassistant homeassistant 4096 sep  2 13:34 .
drwxrwxr-x 7 homeassistant homeassistant 4096 sep  2 13:34 ..
-rw-r--r-- 1 homeassistant homeassistant 4639 sep  2 12:38 device_tracker.py
-rw-r--r-- 1 homeassistant homeassistant   48 sep  2 12:38 __init__.py
-rw-r--r-- 1 homeassistant homeassistant  346 sep  2 12:38 manifest.json
drwxr-xr-x 2 homeassistant homeassistant 4096 sep  2 13:34 __pycache__

google-chrome-stable/stable,now 76.0.3809.132-1 amd64 [installed]

**Comment by shr00mie** [comment]
@redstar2k1 
`sudo mv init.py __init__.py`
then give it a restart.
__init__.py indicates package. don't know if that's the problem, but it sure can't be helping.

**Comment by redstar2k1** [comment]
Indeed the file names are with underscore, just got formatted wrong here.
Yes, I'm running under venv

**Comment by shr00mie** [comment]
@redstar2k1 

ok...so...ubuntu server...but you're running HA in a venv...google-chrome was probably not installed under the venv...what that probably means is that the venv is clueless about chrome's path...might need to hard code google-chrome binary into browser.py...

might just be spitballing...when you get a sec, replace the browser_init section under browser.py with the below and let me know if your box starts smoking:

```python
    def browser_init(self):

        L = randrange(668,868,1)
        W = randrange(924,1124,1)

        log.debug('Setting up webdriver Chrome options.')
        chrome_options = Options()
        chrome_options.binary_location = '/usr/bin/google-chrome-stable'
        prefs = {
                'DefaultJavaScriptSetting': 2,
                'DefaultGeolocationSetting': 2,
                'EnableMediaRouter': False,
                'PasswordManagerEnabled': False,
                'PrintingEnabled': False,
                'CloudPrintProxyEnabled': False,
                'SafeBrowsingExtendedReportingEnabled': False,
                'AutofillAddressEnabled': False,
                'BrowserSignin': 0,
                'BuiltInDnsClientEnabled': False,
                'CommandLineFlagSecurityWarningsEnabled': False,
                'MetricsReportingEnabled': False,
                'NetworkPredictionOptions': 2,
                'SavingBrowserHistoryDisabled': True,
                'SearchSuggestEnabled': False,
                'SpellCheckServiceEnabled': False,
                'SyncDisabled': True,
                'TranslateEnabled': False,
                'UrlKeyedAnonymizedDataCollectionEnabled': False
                }
        chrome_options.add_experimental_option('prefs', prefs)
        chrome_options.add_argument('--user-data-dir={}'.format(self.config.path_chrome))
        chrome_options.add_argument('--window-size={}x{}'.format(L,W))
        chrome_options.add_argument('--disable-plugin-discovery')
        chrome_options.add_argument('--disable-extensions')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.headless = True
        return webdriver.Chrome(options=chrome_options)
```

**Comment by redstar2k1** [comment]
You were missing a try: but I've got that.
Still after making the change (and deleting the pycache) I get the same:

Sep  4 22:40:00 server hass[24913]: 2019-09-04 22:40:00 DEBUG (SyncWorker_7) [gmapslocsharing] Initializing GoogleMaps module.
Sep  4 22:40:00 server hass[24913]: 2019-09-04 22:40:00 DEBUG (SyncWorker_7) [gmapslocsharing.core.config] Initializing Config module.
Sep  4 22:40:00 server hass[24913]: 2019-09-04 22:40:00 ERROR (SyncWorker_7) [custom_components.google_maps.device_tracker] Google Maps - Component configuration failed: list index out of range.

The google chrome path is correct:
root@server:/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing# ll /usr/bin/google-chrome-stable 
lrwxrwxrwx 1 root root 32 aug 24 01:09 /usr/bin/google-chrome-stable -> /opt/google/chrome/google-chrome*

Anything else comes to your mind, let me know, happy to help you debug this.

**Comment by shr00mie** [comment]
@redstar2k1
i took out the try on purpose. they're a double edged sword sometimes and for the sake of convenience, you end up basically masking a potentially blatantly clear stack trace which could resolve the issue in like 3 seconds. so go ahead and yank the try & except parts out or comment and let me know if it's throwing any more info back at ya.

**Comment by redstar2k1** [comment]
With the exact code you gave, I get this:
`Sep  5 08:06:24 server hass[13578]: 2019-09-05 08:06:24 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
Sep  5 08:06:24 server hass[13578]: Traceback (most recent call last):
Sep  5 08:06:24 server hass[13578]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/device_tracker/setup.py", line 77, in async_setup_legacy
Sep  5 08:06:24 server hass[13578]:     discovery_info,
Sep  5 08:06:24 server hass[13578]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Sep  5 08:06:24 server hass[13578]:     result = self.fn(*self.args, **self.kwargs)
Sep  5 08:06:24 server hass[13578]:   File "/home/homeassistant/.homeassistant/custom_components/google_maps/device_tracker.py", line 57, in setup_scanner
Sep  5 08:06:24 server hass[13578]:     scanner = GoogleMapsScanner(hass, config, see)
Sep  5 08:06:24 server hass[13578]:   File "/home/homeassistant/.homeassistant/custom_components/google_maps/device_tracker.py", line 65, in __init__
Sep  5 08:06:24 server hass[13578]:     from gmapslocsharing import GoogleMaps
Sep  5 08:06:24 server hass[13578]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/__init__.py", line 2, in <module>
Sep  5 08:06:24 server hass[13578]:     from .core.browser import Browser
Sep  5 08:06:24 server hass[13578]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/core/browser.py", line 69
Sep  5 08:06:24 server hass[13578]:     except Exception as e:
Sep  5 08:06:24 server hass[13578]:          ^
Sep  5 08:06:24 server hass[13578]: SyntaxError: invalid syntax
`

**Comment by redstar2k1** [comment]
Also if I take out the except and log.debug lines at the end, I get

> Sep  5 08:16:04 server hass[16935]: 2019-09-05 08:16:04 DEBUG (SyncWorker_19) [gmapslocsharing] Initializing GoogleMaps module.
> Sep  5 08:16:04 server hass[16935]: 2019-09-05 08:16:04 DEBUG (SyncWorker_19) [gmapslocsharing.core.config] Initializing Config module.
> Sep  5 08:16:04 server hass[16935]: 2019-09-05 08:16:04 ERROR (SyncWorker_19) [custom_components.google_maps.device_tracker] Google Maps - Component configuration failed: list index out of range.
>

**Comment by shr00mie** [comment]
under custom_components/device_tracker.py, replace the `__init__` section under the GoogleMapsScanner class with the below:
```python
    def __init__(self, hass, config: ConfigType, see) -> None:
        """Initialize the scanner."""
        from gmapslocsharing import GoogleMaps
        self.see = see
        self.username = config[CONF_USERNAME]
        self.password = config[CONF_PASSWORD]
        self.debug = config[CONF_DEBUG]
        self.max_gps_accuracy = config[CONF_MAX_GPS_ACCURACY]

        self.service = GoogleMaps(
                                    self.username,
                                    self.password,
                                    hass.config.path(),
                                    self.debug
                                    )
        track_time_interval(
                            hass,
                            self._update_info,
                            MIN_TIME_BETWEEN_SCANS
                            )
```

**Comment by redstar2k1** [comment]
```
Sep  5 09:05:23 server hass[722]: 2019-09-05 09:05:23 DEBUG (SyncWorker_12) [gmapslocsharing] Initializing GoogleMaps module.
Sep  5 09:05:23 server hass[722]: 2019-09-05 09:05:23 DEBUG (SyncWorker_12) [gmapslocsharing.core.config] Initializing Config module.
Sep  5 09:05:23 server hass[722]: 2019-09-05 09:05:23 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
Sep  5 09:05:23 server hass[722]: Traceback (most recent call last):
Sep  5 09:05:23 server hass[722]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/device_tracker/setup.py", line 77, in async_setup_legacy
Sep  5 09:05:23 server hass[722]:     discovery_info,
Sep  5 09:05:23 server hass[722]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Sep  5 09:05:23 server hass[722]:     result = self.fn(*self.args, **self.kwargs)
Sep  5 09:05:23 server hass[722]:   File "/home/homeassistant/.homeassistant/custom_components/google_maps/device_tracker.py", line 57, in setup_scanner
Sep  5 09:05:23 server hass[722]:     scanner = GoogleMapsScanner(hass, config, see)
Sep  5 09:05:23 server hass[722]:   File "/home/homeassistant/.homeassistant/custom_components/google_maps/device_tracker.py", line 76, in __init__
Sep  5 09:05:23 server hass[722]:     self.debug
Sep  5 09:05:23 server hass[722]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/__init__.py", line 18, in __init__
Sep  5 09:05:23 server hass[722]:     self.config = Config(self.path, debug)
Sep  5 09:05:23 server hass[722]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/core/config.py", line 122, in __init__
Sep  5 09:05:23 server hass[722]:     Config.instance = Config.__Config(config_path, debug)
Sep  5 09:05:23 server hass[722]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/core/config.py", line 18, in __init__
Sep  5 09:05:23 server hass[722]:     self.startup()
Sep  5 09:05:23 server hass[722]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/core/config.py", line 25, in startup
Sep  5 09:05:23 server hass[722]:     ][0] \
Sep  5 09:05:23 server hass[722]: IndexError: list index out of range

```

**Comment by shr00mie** [comment]
think i found the issue. gonna have to wait till i recharge.

**Comment by shr00mie** [comment]
@redstar2k1 
which branch were you pulling from? master?

**Comment by redstar2k1** [comment]
@shr00mie Yes, master branch

**Comment by shr00mie** [comment]
@redstar2k1 
k. give me like 10-15. trying to figure out the math behind sunrise/sunset calculations...

**Comment by shr00mie** [comment]
ok. so...what i'll leave you with is don't ever look into how to calculate sunrise and sunset for your specific geolocation.

in other news, bunch of stuff pushed to master. give it a go and let me know where we're at.

**Comment by redstar2k1** [comment]
Unfortunately, with the latest master branch, my HA just crash on restart:

> Sep  8 12:40:32 server hass[21024]: 2019-09-08 12:40:32 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of ruamel.yaml==0.15.42
> Sep  8 12:40:32 server hass[21024]: Config directory: /home/homeassistant/.homeassistant
> Sep  8 12:40:35 server hass[21024]: Traceback (most recent call last):
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/bin/hass", line 10, in <module>
> Sep  8 12:40:35 server hass[21024]:     sys.exit(main())
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/__main__.py", line 401, in main
> Sep  8 12:40:35 server hass[21024]:     exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/async_.py", line 37, in asyncio_run
> Sep  8 12:40:35 server hass[21024]:     return loop.run_until_complete(main)
> Sep  8 12:40:35 server hass[21024]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
> Sep  8 12:40:35 server hass[21024]:     return future.result()
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/__main__.py", line 304, in setup_and_run_hass
> Sep  8 12:40:35 server hass[21024]:     log_no_color=args.log_no_color,
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/bootstrap.py", line 139, in async_from_config_file
> Sep  8 12:40:35 server hass[21024]:     config_dict, hass, enable_log=False, skip_pip=skip_pip
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/bootstrap.py", line 95, in async_from_config_dict
> Sep  8 12:40:35 server hass[21024]:     await _async_set_up_integrations(hass, config)
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/bootstrap.py", line 365, in _async_set_up_integrations
> Sep  8 12:40:35 server hass[21024]:     *(async_setup_component(hass, domain, config) for domain in domains_to_load)
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/config_entries.py", line 562, in async_forward_entry_setup
> Sep  8 12:40:35 server hass[21024]:     result = await async_setup_component(self.hass, domain, self._hass_config)
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 46, in async_setup_component
> Sep  8 12:40:35 server hass[21024]:     return await setup_tasks[domain]  # type: ignore
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/config_entries.py", line 562, in async_forward_entry_setup
> Sep  8 12:40:35 server hass[21024]:     result = await async_setup_component(self.hass, domain, self._hass_config)
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 46, in async_setup_component
> Sep  8 12:40:35 server hass[21024]:     return await setup_tasks[domain]  # type: ignore
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 52, in async_setup_component
> Sep  8 12:40:35 server hass[21024]:     return await task  # type: ignore
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 137, in _async_setup_component
> Sep  8 12:40:35 server hass[21024]:     hass, config, integration
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/config.py", line 767, in async_process_component_config
> Sep  8 12:40:35 server hass[21024]:     platform = p_integration.get_platform(domain)
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 235, in get_platform
> Sep  8 12:40:35 server hass[21024]:     "{}.{}".format(self.pkg_path, platform_name)
> Sep  8 12:40:35 server hass[21024]:   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
> Sep  8 12:40:35 server hass[21024]:     return _bootstrap._gcd_import(name[level:], package, level)
> Sep  8 12:40:35 server hass[21024]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
> Sep  8 12:40:35 server hass[21024]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> Sep  8 12:40:35 server hass[21024]:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> Sep  8 12:40:35 server hass[21024]:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
> Sep  8 12:40:35 server hass[21024]:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
> Sep  8 12:40:35 server hass[21024]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> Sep  8 12:40:35 server hass[21024]:   File "/home/homeassistant/.homeassistant/custom_components/google_maps/device_tracker.py", line 8, in <module>
> Sep  8 12:40:35 server hass[21024]:     from gmapslocsharing import GoogleMaps
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/__init__.py", line 1, in <module>
> Sep  8 12:40:35 server hass[21024]:     from .core.location import Location
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/core/location.py", line 3, in <module>
> Sep  8 12:40:35 server hass[21024]:     from .config import Config
> Sep  8 12:40:35 server hass[21024]:   File "/srv/homeassistant/lib/python3.6/site-packages/gmapslocsharing/core/config.py", line 47
> Sep  8 12:40:35 server hass[21024]:     except:
> Sep  8 12:40:35 server hass[21024]:          ^
> Sep  8 12:40:35 server hass[21024]: SyntaxError: invalid syntax
> Sep  8 12:40:35 server hass[21024]: 2019-09-08 12:40:35 ERROR (SyncWorker_2) [concurrent.futures] exception calling callback for <Future at 0x7f04f9c79f98 state=finished returned bool>
> Sep  8 12:40:35 server hass[21024]: Traceback (most recent call last):
> Sep  8 12:40:35 server hass[21024]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
> Sep  8 12:40:35 server hass[21024]:     callback(self)
> Sep  8 12:40:35 server hass[21024]:   File "/usr/lib/python3.6/asyncio/futures.py", line 417, in _call_set_state
> Sep  8 12:40:35 server hass[21024]:     dest_loop.call_soon_threadsafe(_set_state, destination, source)
> Sep  8 12:40:35 server hass[21024]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 637, in call_soon_threadsafe
> Sep  8 12:40:35 server hass[21024]:     self._check_closed()
> Sep  8 12:40:35 server hass[21024]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
> Sep  8 12:40:35 server hass[21024]:     raise RuntimeError('Event loop is closed')
> Sep  8 12:40:35 server hass[21024]: RuntimeError: Event loop is closed
>

**Comment by shr00mie** [comment]
sorry bout that. had a couple indents sneak in. changes pushed.

**Comment by redstar2k1** [comment]
IT IS ALIVE ! :)
Thank's man, great work, will keep using it and let you know how's working.
